### ISSUE TITLE
not valid になる画像 (Jpeg品質60/40、低解像度機)

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#139]
条件が特殊なので、滅多に問題にならないと思いますが、以下の2点から、この画像に特有の問題を含む可能性があるため、念のために報告いたします

- この画像だけ複数の設定でnot validになっていた
- 他のクエストでは品質60で認識率100%だった

(ここまで低い品質で使う人は少ないと思いますので、)優先度は低めでいいと思います

コード：
```
python fgosccnt.py IMG_1122.jpg
```
出力結果：
```
filename,ドロ数
IMG_1122.jpg: not valid,
```

**品質60**
![IMG_1122](https://user-images.githubusercontent.com/6458565/89350908-de181400-d6eb-11ea-8c24-5aa97a7d2593.jpg)

**品質40**
![IMG_1122](https://user-images.githubusercontent.com/6458565/89351360-d311b380-d6ec-11ea-8fe4-cc6885f93a07.jpg)

**Original**
![IMG_1122](https://user-images.githubusercontent.com/6458565/89351402-e45ac000-d6ec-11ea-807f-7d6301652bb9.PNG)

![第二階層 極光の間（裏）test](https://user-images.githubusercontent.com/6458565/89351146-5a125c00-d6ec-11ea-85a6-f4d0ae6b9c3f.png)

**Comment by fgophi** [comment]
品質を落としていけば必ずどこかで不具合が起きますが、とりあえずこれらのファイルはpageinfo.py が処理できない状態です

```
$ python fgosccnt.py IMG_1122_40.jpg
Traceback (most recent call last):
  File "../fgosccnt.py", line 1698, in <module>
    fileoutput, all_new_list = get_output(inputs, args)
  File "../fgosccnt.py", line 1507, in get_output
    sc = ScreenShot(img_rgb, svm, svm_chest, svm_card, fileextention, debug)
  File "../fgosccnt.py", line 114, in __init__
    self.pagenum, self.pages, self.lines = pageinfo.guess_pageinfo(img_rgb)
  File "C:\Users\nono_000\Documents\git\dev9\fgosccnt\pageinfo.py", line 375, in guess_pageinfo
    pages = guess_pages(asr_w, asr_h, esr_w, esr_h)
  File "C:\Users\nono_000\Documents\git\dev9\fgosccnt\pageinfo.py", line 180, in guess_pages
    raise CannotGuessError(
pageinfo.CannotGuessError: 幅の誤差が大きすぎます: delta = 10, entire_width = 39, actual_width = 29
```

**Comment by amenohimo** [comment]
@max747
やってみます

**Comment by amenohimo** [comment]
@max747

 `thresholds_for_entire = range(36, 17, -1)` に変更後、以下の変化がありました。
 
1. [IMG_1122.PNG](https://user-images.githubusercontent.com/6458565/89351402-e45ac000-d6ec-11ea-807f-7d6301652bb9.PNG)を変換した画像は、[品質40](https://user-images.githubusercontent.com/6458565/89351360-d311b380-d6ec-11ea-8fe4-cc6885f93a07.jpg)、品質50、[品質60](https://user-images.githubusercontent.com/6458565/89350908-de181400-d6eb-11ea-8c24-5aa97a7d2593.jpg)においても認識するようになりました。それに伴い、今回用意した「極光の間 (裏)」の品質40と品質60は完全に認識するようになりました。

2. 品質50において、新たに[IMG_1451.jpg](https://user-images.githubusercontent.com/6458565/91971761-af29a800-ed54-11ea-9081-fb88ad8d0eda.jpg)-[IMG_1452.jpg](https://user-images.githubusercontent.com/6458565/91971763-b0f36b80-ed54-11ea-99d1-af9d7a74020b.jpg)間がmissingになり、[IMG_1452.jpg](https://user-images.githubusercontent.com/6458565/91971763-b0f36b80-ed54-11ea-99d1-af9d7a74020b.jpg)において1つの素材を15と誤認識するようになりました。

![無題](https://user-images.githubusercontent.com/6458565/91971495-404c4f00-ed54-11ea-91f1-267f307d6b03.png)
![2](https://user-images.githubusercontent.com/6458565/91971644-81446380-ed54-11ea-813c-bd2c7e022620.png)


以下、品質50において、「not valid」あるいは「missing」になっていたjpg画像です

**IMG_1446.jpg**
![IMG_1446.jpg](https://user-images.githubusercontent.com/6458565/91973042-860a1700-ed56-11ea-9a77-5582dcc3a5b5.jpg)

**IMG_1451.jpg**
![IMG_1451.jpg](https://user-images.githubusercontent.com/6458565/91971761-af29a800-ed54-11ea-9081-fb88ad8d0eda.jpg)

**IMG_1452.jpg**
![IMG_1452.jpg](https://user-images.githubusercontent.com/6458565/91971763-b0f36b80-ed54-11ea-99d1-af9d7a74020b.jpg)

**IMG_1454.jpg**
![IMG_1454.jpg](https://user-images.githubusercontent.com/6458565/91973256-e6995400-ed56-11ea-951e-ca1331348170.jpg)

**IMG_1459.jpg**
![IMG_1459.jpg](https://user-images.githubusercontent.com/6458565/91973286-f3b64300-ed56-11ea-89c3-0fe5f3205015.jpg)

**IMG_1462.jpg**
![IMG_1462.jpg](https://user-images.githubusercontent.com/6458565/91973293-f9138d80-ed56-11ea-89a7-8c745fa72553.jpg)

**Comment by max747** [comment]
やはりそれほど簡単に解決はしませんね。品質の低いJPEGはサポート対象外の方向かな...

**Comment by amenohimo** [comment]
他のクエストも試していますが、品質40で通るところが多いので、ここの品質50だけ特殊なのか、あるいは品質50に問題があるのかもと思っています
品質40よりも品質50がダメなのが不思議ですね
