### ISSUE TITLE
not validになる画像

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#239]
```
filename,ドロ数
R:\IMG_4749.PNG: not valid,
```

```
$ "D:\_programs\Python\python.exe" "D:\_programs\fgosccnt\fgosccnt.py" R:\IMG_4749.PNG
__main__ <fgosccnt.py-L2261> [ERROR] OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
Traceback (most recent call last):
  File "D:\_programs\fgosccnt\fgosccnt.py", line 2179, in get_output
    sc = ScreenShot(args, img_rgb,
  File "D:\_programs\fgosccnt\fgosccnt.py", line 205, in __init__
    dcnt_old_rs = cv2.resize(dcnt_old, (0, 0),
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

IMG_4749
![IMG_4749](https://user-images.githubusercontent.com/6458565/102465524-17e12a00-4091-11eb-9127-8ff6c6c77ba8.PNG)

**Comment by fgophi** [comment]
最新のmasterではこの現象は確認できないので最新のmasterにアップデートしてください

**Comment by amenohimo** [comment]
了解です！

**Comment by amenohimo** [comment]
直りました！
```filename,ドロ数,報酬QP(+4400),礼装,蛇玉,バンテージ(x2),バンテージ(x3),バナナ(x3),ガム(x3)
R:\IMG_4749.PNG,20,1,,1,7,3,7,2
```

お騒がせしました！（ﾍﾟｺﾘ
