### ISSUE TITLE
not validになる画像

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#246]
```
filename,ドロ数,礼装,バー(x3),ガム(x3)
合計,,0,3,6
R:\IMG_5194.PNG: not valid,,,,
missing,,,,
R:\IMG_5195.PNG,9,,3,6
```

```
$ python fgosccnt.py R:\IMG_5194.PNG R:\IMG_5195.PNG
__main__ <fgosccnt.py-L598> [WARNING] right_x detection failed.
__main__ <fgosccnt.py-L2275> [ERROR] OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
Traceback (most recent call last):
  File "D:\_programs\fgosccnt\fgosccnt.py", line 2187, in get_output
    sc = ScreenShot(args, img_rgb,
  File "D:\_programs\fgosccnt\fgosccnt.py", line 208, in __init__
    dcnt_new_rs = cv2.resize(dcnt_new, (0, 0),
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'
```

![IMG_5194](https://user-images.githubusercontent.com/6458565/102591258-15e09f00-4155-11eb-9d24-296c26162149.PNG)
![IMG_5195](https://user-images.githubusercontent.com/6458565/102591267-1842f900-4155-11eb-8267-2e89ebe83311.PNG)

**Comment by fgophi** [comment]
「獲得した戦利品」の文字下の破線が直線判定されないのが原因です
![image](https://user-images.githubusercontent.com/62515228/102608242-ef2e6280-416c-11eb-8307-3b3aa3928eb6.png)

最新版では直線判定するよう変更しましたが、他のスクショで悪影響でるようなら取り消すかもしれません
