### ISSUE TITLE
not valid (情報バー)

### ISSUE THREAD

**Issue by amenohimo** [fgosc/fgosccnt#265]
![notvalid](https://user-images.githubusercontent.com/6458565/123918332-ba725200-d9be-11eb-97f6-0d815d660191.PNG)

```
$ fgosccnt *
__main__ <fgosccnt.py-L2331> [ERROR] notvalid.PNG
__main__ <fgosccnt.py-L2332> [ERROR] OpenCV(4.2.0) C:\projects\opencv-python\ope
ncv\modules\imgproc\src\resize.cpp:4045: error: (-215:Assertion failed) !ssize.e
mpty() in function 'cv::resize'
Traceback (most recent call last):
  File "D:/_programs/fgosccnt/fgosccnt.py", line 2243, in get_output
    sc = ScreenShot(args, img_rgb,
  File "D:/_programs/fgosccnt/fgosccnt.py", line 209, in __init__
    dcnt_new_rs = cv2.resize(dcnt_new, (0, 0),
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\imgproc\src\re
size.cpp:4045: error: (-215:Assertion failed) !ssize.empty() in function 'cv::re
size'

filename,ドロ数
notvalid.PNG: not valid,
```

今のところ、表題の条件でnot validになったのはこの1枚だけです

**Comment by fgophi** [comment]
@amenohimo 
画面の切り出し方を変更した現行バージョンではnot validは出ず、結果の認識も #262 の問題がでていないのでcloseします
